### ISSUE TITLE
[BUG] Some problems with 0.17.6 version

### ISSUE THREAD

**Issue by YesSkyscrapers** [inappstory/react-native-sdk-v2#1]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@inappstory/react-native-sdk@0.17.6` for the project I'm working on.

1) sandbox: boolean = true; 
I got feedEvents = [] when sandbox == true
Just no stories.
Check our prev solution with native sdk... We create IAS with only 2 parametrs (userId, apiKey). So I changed sandbox to false, and started receive stories.

2) font changes was not applied to types. Yes, I can use them in JavaScript, but if I want to use them in Typescript I forced to pass parametrs with "any"

3) onViewableItemsChanged
I got error: "Changing onViewableItemsChanged on the fly is not supported"
Link - https://github.com/facebook/react-native/issues/30171
You just recreate function with every render, so cause this error. Just wrapped with useCallback func.
Also moved it to before "if", because numbers of hook shouldn't differ between renders.
Link - https://stackoverflow.com/questions/60582036/react-native-rendered-more-hooks-than-during-the-previous-render-error

4) useTextureView={true}
react-native-video provides "useTextureView" - https://thewidlarzgroup.github.io/react-native-video/component/props#usetextureview
Its allow to use SurfaceView that "It can't be animated, transformed or scaled"
But we have 4 stories. One of them is video. And all stories opened: true, so they all applied changed opacity.
SurfaceView not allow to change it, so 3 stories looks like opened, but one with video no.
If we changing it to useTextureView, so we have Story with video that can be modified with opacity prop.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@inappstory/react-native-sdk/src/index.ts b/node_modules/@inappstory/react-native-sdk/src/index.ts
index 305bbb4..6f5e812 100644
--- a/node_modules/@inappstory/react-native-sdk/src/index.ts
+++ b/node_modules/@inappstory/react-native-sdk/src/index.ts
@@ -209,7 +209,7 @@ export class StoryManager {
   lang: string = '';
   soundEnabled: boolean = true;
   getGoodsCallback: Function = () => {};
-  sandbox: boolean = true;
+  sandbox: boolean = false;
   sendStatistics: boolean = true;
   listeners: any = [];
   constructor(config: StoryManagerConfig) {
@@ -692,6 +692,10 @@ export declare type StoriesListCardOptions = Partial<{
     color: string;
     padding: string | number;
     font: string;
+    fontSize: number;
+    fontWeight: string | number;
+    fontFamily: string;
+    lineHeight: number;
     display: boolean;
     textAlign: StoriesListCardTitleTextAlign;
     position: StoriesListCardTitlePosition;
diff --git a/node_modules/@inappstory/react-native-sdk/src/stories/StoriesCarousel.tsx b/node_modules/@inappstory/react-native-sdk/src/stories/StoriesCarousel.tsx
index 8feca15..b2b6bdd 100644
--- a/node_modules/@inappstory/react-native-sdk/src/stories/StoriesCarousel.tsx
+++ b/node_modules/@inappstory/react-native-sdk/src/stories/StoriesCarousel.tsx
@@ -83,15 +83,7 @@ export const StoriesCarousel = ({
     }
   };
 
-  if (typeof stories === 'undefined' || !stories.length)
-    return (
-      <View
-        style={{
-          height: appearanceManager?.storiesListOptions.card.height + 7,
-        }}
-      />
-    );
-  const onViewableItemsChanged = (items) => {
+  const onViewableItemsChanged = React.useCallback((items) => {
     const newIDs = items.changed
       .filter((i) => i.isViewable)
       .map((i) => String(i.key))
@@ -103,7 +95,17 @@ export const StoriesCarousel = ({
     if (newIDs.length > 0) {
       InAppStorySDK.setVisibleWith(newIDs);
     }
-  };
+  }, []);
+
+  if (typeof stories === 'undefined' || !stories.length)
+    return (
+      <View
+        style={{
+          height: appearanceManager?.storiesListOptions.card.height + 7,
+        }}
+      />
+    );
+  
   let datasource: any = [];
   if (favoritesOnly) {
     datasource = favoriteStories;
diff --git a/node_modules/@inappstory/react-native-sdk/src/stories/StoryComponent.tsx b/node_modules/@inappstory/react-native-sdk/src/stories/StoryComponent.tsx
index ea5143d..06785f4 100644
--- a/node_modules/@inappstory/react-native-sdk/src/stories/StoryComponent.tsx
+++ b/node_modules/@inappstory/react-native-sdk/src/stories/StoryComponent.tsx
@@ -91,7 +91,7 @@ export const StoryComponent = ({
         paused={false}
         playInBackground={true}
         playWhenInactive={true}
-        useTextureView={false}
+        useTextureView={true}
         disableFocus={true}
       />
       {coverOverlay}
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by artyom-89** [comment]
Hello @YesSkyscrapers Thank you for your bug report (and patch-package diff).

1. sandbox - this public API allows SDK to use our test server instead of production
mistakenly made it default to true
but now this functionality is not needed, so it was removed from the public api of SDK (in v0.18.0)
2. fixed in v0.18.0
3. fixed in v0.18.0
4. fixed in v0.18.0
